# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Replace with your branch name

pr:
- '*'

pool:
  name: 'test'  # Replace with your agent pool name

steps:
- script: '/opt/apache-maven-3.9.5/bin/mvn clean install'
  displayName: 'Build Maven Project'


