# Starter pipeline


name: demo on parameters
parameters:
  - name: projectname
    type: string
    default: version
    values: 
      - admin
      - payment
      - profile

  - name: deploy
    type: boolean
    default: false

pool:
  name: 'test'

  steps:
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      msbuildArgs: "/t: ${{ parameters.projectname }}"
